# ===================================================================== #
#                                                                       #
#   ::::::::  :::::::::  :::::::::  ::::::::::: ::::    :::  ::::::::   #
#  :+:    :+: :+:    :+: :+:    :+:     :+:     :+:+:   :+: :+:    :+:  #
#  +:+        +:+    +:+ +:+    +:+     +:+     :+:+:+  +:+ +:+         #
#  +#++:++#++ +#++:++#+  +#++:++#:      +#+     +#+ +:+ +#+ :#:         #
#         +#+ +#+        +#+    +#+     +#+     +#+  +#+#+# +#+   +#+#  #
#  #+#    #+# #+#        #+#    #+#     #+#     #+#   #+#+# #+#    #+#  #
#   ########  ###        ###    ### ########### ###    ####  ########   #
#                                                                       #
# ===================================================================== #
#                                                                       #
#                        by Efnilite, 2023                              #
#                                                                       #
# ===================================================================== #

# -= Check interval =-
# The interval at which Spring will check for updates in seconds.
# Default = 28800 seconds.
check_interval: 28800

# -= Restart =-
# Settings for automatic restarts.
restart:

  interval: [24, 0, 0]

  warning: "Restarting in %s second(s)."

  warning_interval: [180, 120, 60, 30, 10, 5, 4, 3, 2, 1]

  kick_message: "Restarting. Please rejoin."